server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: mall-goods
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.122.133
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1i3l1n8d7713xt24o.mysql.rds.aliyuncs.com:3306/shop_goods?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    username: root
    password: zxy971225!

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-spring.xml
