server:
  port: 8085

spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.122.133
    gateway:
      routes:
        id: baidu
        uri: https://www.baidu.com


