server:
  port: 8085

spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
       - id: mall-goods
         uri: lb://mall-goods
         predicates:
           - Path=/mall-goods/**
       - id: mall-order
         uri: lb://mall-order
         predicates:
           - Path=/mall-order/**
  redis:
    host: localhost
    password: 12

