server:
  port: 8084
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: mall-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos注册中心地址

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zxy971225!
    url: jdbc:mysql://rm-bp1i3l1n8d7713xt24o.mysql.rds.aliyuncs.com:3306/shop_orders?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-spring.xml
